name: C/C++ CI

env:
  ZIG_VERSION: zig-linux-x86_64-0.12.0-dev.696+9a001e1f7

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - name: Download zig
      run: |
        cd $GITHUB_WORKSPACE
        curl -L -O https://ziglang.org/builds/$ZIG_VERSION.tar.xz
        tar -xf $ZIG_VERSION.tar.xz
        
    - name: Build hermes
      run: |
        cd $GITHUB_WORKSPACE
        sudo apt update
        sudo apt install cmake git ninja-build libicu-dev zip libreadline-dev
        git clone https://github.com/facebook/hermes.git
        export PATH=$GITHUB_WORKSPACE/$ZIG_VERSION/:$PATH
        export CC="zig cc -O3 -fno-sanitize=undefined"
        export CXX="zig c++ -O3 -fno-sanitize=undefined"
        cmake -S hermes -B build -G Ninja
        cmake --build ./build
