name: Hermes Build

env:
  ZIG_VERSION: zig-linux-x86_64-0.12.0-dev.696+9a001e1f7
  CC: zig cc -O2 -fno-sanitize=undefined
  CXX: zig c++ -O2 -fno-sanitize=undefined

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - name: Download zig
      run: |
        cd $GITHUB_WORKSPACE
        curl -L -O https://ziglang.org/builds/$ZIG_VERSION.tar.xz
        tar -xf $ZIG_VERSION.tar.xz
        
    - name: Build hermes
      run: |
        cd $GITHUB_WORKSPACE
        sudo apt update
        sudo apt install cmake git ninja-build libicu-dev zip libreadline-dev
        git clone https://github.com/facebook/hermes.git
        export PATH=$GITHUB_WORKSPACE/$ZIG_VERSION/:$PATH
        cmake -S hermes -B build_release -G Ninja -DCMAKE_BUILD_TYPE=Release
        cmake --build ./build_release



    - name: Upload Hermes Build
      uses: actions/upload-artifact@v3.1.3
      with: 
        path: |
          ${{ github.workspace }}/build_release
          !${{ github.workspace }}/build_release/unittests/**

