name: Hermes Build

env:
  ZIG_VERSION: zig-linux-x86_64-0.12.0-dev.696+9a001e1f7
  CC: "zig cc"
  CXX: "zig c++"
  #CFLAGS: "-O3 -fno-sanitize=undefined"
  #CXXFLAGS: "-O3 -fno-sanitize=undefined"

on:
  push:
    tags: 
      - '*'
  workflow_dispatch:
    inputs:
      version:
  create:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ inputs.version }}',
              sha: context.sha
          })
    
    - name: Download zig
      run: |
        cd $GITHUB_WORKSPACE
        curl -L -O https://ziglang.org/builds/$ZIG_VERSION.tar.xz
        tar -xf $ZIG_VERSION.tar.xz
        
    - name: Build hermes
      run: |
        cd $GITHUB_WORKSPACE
        sudo apt update
        sudo apt install cmake git ninja-build libicu-dev zip libreadline-dev
        git clone https://github.com/facebook/hermes.git

        export PATH=$GITHUB_WORKSPACE/$ZIG_VERSION/:$PATH

        cmake -S hermes -B x86_64-linux-hermes_zig -G Ninja -DCMAKE_BUILD_TYPE=Release
        cd x86_64-linux-hermes_zig
        cat build.ninja
      #ninja
      #cd ${{ github.workspace }}
      #tar czf x86_64-linux-hermes_zig.tar.gz ./x86_64-linux-hermes_zig/


    - name: Upload Hermes Build
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ inputs.version }}
        artifacts: "x86_64-linux-hermes_zig.tar.gz"
